openapi: 3.0.0
info:
  version: 1.0.0
  title: Lecture API
  description: description
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Grupa X
    email: niedamswojegomaila@gmail.com
    url: 'http://swagger.io'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  - url: 'http://imdp.swagger.io/v1'
paths: 
  /movies:
    get:
        summary: List all movies
        operationId: listMovies
        tags:
          - movies
        parameters:
          - name: limit
            in: query
            description: How many items to return at one time (max 100)
            required: false
            schema:
              type: integer
              format: int32
        responses:
          '200':
            description: A paged array of movies
            headers:
              x-next:
                description: A link to the next page of responses
                schema:
                  type: string
            content:
              application/json:    
                schema:
                  $ref: "#/components/schemas/Movies"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
    post:
      summary: Create a movie
      operationId: createMovies
      tags:
        - movies
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /series:  
    get:
        get:
        summary: List all series
        operationId: listSeries
        tags:
          - series
        parameters:
          - name: limit
            in: query
            description: How many items to return at one time (max 100)
            required: false
            schema:
              type: integer
              format: int32
        responses:
          '200':
            description: A paged array of series
            headers:
              x-next:
                description: A link to the next page of responses
                schema:
                  type: string
            content:
              application/json:    
                schema:
                  $ref: "#/components/schemas/Series"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
    post:
      summary: Create a series
      operationId: createSeries
      tags:
        - series
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /movies/{movieId}:
      get:
        summary: Info for a specific movie
        operationId: showMovieById
        tags:
          - movies
        parameters:
          - name: movieId
            in: movie
            required: true
            description: The id of the movie to retrieve
            schema:
              type: string
        responses:
          '200':
            description: Expected response to a valid request
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Movies"
          default:
            description: unexpected error
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
  /series/{seriesId}:
        get:
          summary: Info for a specific series
          operationId: showSeriesById
          tags:
            - series
          parameters:
            - name: seriesId
              in: series
              required: true
              description: The id of the series to retrieve
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Series"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"

components:
  schemas:
    Movie:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Movies:
      type: array
      items:
        $ref: "#/components/schemas/Movie"
    Series:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Series/:
      type: array
      items:
        $ref: "#/components/schemas/Series"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string                      
      
     
                                                                          